### ISSUE TITLE
environment variable not evaluated correctly in config

### ISSUE THREAD

**Issue by binoculars** [CenterForOpenScience/ember-osf-preprints#459]
@pattisdr 

https://github.com/CenterForOpenScience/ember-preprints/blob/ddb252cd0cf72a5056737e58b8292b9f543dd485/config/environment.js#L61

```js
[process.env.KEEN_ENVIRONMENT] || ['production']
```

should be:

```js
[process.env.KEEN_ENVIRONMENT || 'production']
```

the first one always evaluates to an array, which is truthy (production never gets referenced). I don't think it affects anything, just for reference. Alternatively, we can use object destructuring with default values.

**Comment by alexschiller** [comment]
@baylee-d is actually fixing this because it did cause some weirdness for a keen related PR. Closing this issue so I don't forget.
