### ISSUE TITLE
Setting up a new preprint server

### ISSUE THREAD

**Issue by Gitubert** [CenterForOpenScience/ember-osf-preprints#484]
Hello,

I would like to set up a new preprint server but I am not a developer. So, my question is: can set up such a server using the EMBER-OSF-Preprint provided here? 
Actually, I downloaded the files but cannot figure out how to install it on Windows (or using webserver such as WAMP) as there is a lot of dependencies and web tools that I do not understand much!

Thank you,
Regards,
G

**Comment by mattspitzer** [comment]
Hi Gitubert,

COS offers a hosted option for OSF preprints using the deployment at osf.io/preprints. We host the service, and your community handles any needed moderation or development of editorial policy.

I can help answer any questions you have on the process setting things up, and there is more information on the standard hosted option here: https://cos.io/our-products/osf-preprints/

Feel free to email me at matt.spitzer@cos.io 

-Matt
COS Community Manager

**Comment by Gitubert** [comment]
Hi Matt,

Thank you for your response.
The idea behind OSF is pretty cool!
A further small question please: should one buy a domain name for his preprints server and setup a corresponding website or only buy a domain name and it will be the OSF that will set it up using the domain name bought by the user?

Thank you once again for your support.

**Comment by mattspitzer** [comment]
We have services doing it both ways. 

Some are running a separate companion website where they host FAQs, blogs, etc. and have that point to the repository. Example: https://socopen.org/

Some have a domain set up and either redirect to their osf.io/preprint/name link, or we can set up their domain as the custom domain for the repository on the OSF. Example: eartharxiv.org

**Comment by alexschiller** [comment]
This looks like it was handled a long time ago. Closing.
